### PR TITLE
Upgraded Rails to 5.1.4

### PR DESCRIPTION
**Pull request by tomca32**

### CODE REVIEW

**Comment by greysteil** [comment]
@tomca32 - would you be up for automatically creating PRs like this one? I built [Dependabot](https://dependabot.com) to do that, and it's free for open source (and always will be).

**Comment by tomca32** [comment]
Hi @greysteil, sorry didn't see your comment before.
Thank you for the suggestion; however, we already use @deppbot for that, and we're pretty happy with it.
That said, Dependabot looks pretty nice and I will definitely consider using it in other projects.

Thanks

**Comment by greysteil** [comment]
Ah cool, yeah, Deppbot is pretty good!

**Comment by tomca32** [comment]
It is, yes. However, I like the multi-language support in Dependabot, so I might try it with some other projects. Docker support is a nice touch

**Pull request merged**
