### PR TITLE
Track 4 - Grading

### PR DESCRIPTION
**Pull request by tomca32**
Grading is done through lessons. Clicking on a lesson will bring a list of students who participated in the lesson. Clicking a particular student will bring up a grading screen.

### CODE REVIEW

**Comment by tomca32** [comment]
@j16r - This is a biggie. Understand if it's too big to go over, but maybe just sanity check to see if there's some glaring problems.

Should have split this up into multiple stories but c'est la vie.

**Comment by tomca32** [comment]
Yeah! Coverage increase!

**Comment by tomca32** [comment]
Not sure what's up with feature spec. Fails with "MouseEvent failed" - works fine locally, kicking off again.

**Comment by j16r** [comment]
Didn't get a chance to review this, but overall looks very clean!

**Comment by tomca32** [comment]
Thanks for taking a look! Totally understand the lack of time to properly review especially since it's pretty long.

**Pull request merged**
